name: hello-world
on:
  push:
    branches:
      - 'main'
jobs:
 my-job:
   runs-on: ubuntu-latest
   needs: build
   steps:
    - name: my-step
      run: echo "hello-world"
 build:
   runs-on: ubuntu-latest
   steps:
    - name: my-step
      run: echo "hello-world"
